name: Self update testing
on: push
jobs:
  # Checkout in separate job because docker image is alpine based and checkout action doesn't work.
  functional:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: self-update-fixture
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    name: Run functional tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: self-update
      - name: Checkout self-update-fixtures
        uses: actions/checkout@v2
        with:
          repository: kporras07/self-update-fixture
          path: self-update-fixture
          ref: self-update
      - name: Run Composer Install
        run: composer install
      - name: Add path repository
        run: composer config repositories.self-update path ../self-update
      - name: Require self-update package
        run: COMPOSER_MIRROR_PATH_REPOS=1 composer require consolidation/self-update:"*"
      - name: Phar Build
        run: composer phar:build
      - name: Get current version
        run: ./wonder info | grep "1.2"
      - name: Backup current wonder binary
        run: cp ./wonder ./wonder-backup
      - name: Self update --stable
        run: cp -r ./wonder-backup wonder && ./wonder self:update --stable && ./wonder info | grep "2.0"
      - name: Self update
        run: cp -r ./wonder-backup wonder && ./wonder self:update && ./wonder info | grep "2.0"
      - name: Self update --preview
        run: cp -r ./wonder-backup wonder && ./wonder self:update --preview && ./wonder info | grep "2.1-beta1"
      - name: Self update --stable --compatible
        run: cp -r ./wonder-backup wonder && ./wonder self:update --stable --compatible && ./wonder info | grep "1.3"
      - name: Self update --compatible
        run: cp -r ./wonder-backup wonder && ./wonder self:update --compatible && ./wonder info | grep "1.3"
